# Generated by Django 5.0.1 on 2024-05-06 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_broker_fb_link_alter_group_fb_id'),
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.company'),
        ),
    ]
