# Generated by Django 5.0.1 on 2024-01-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brokers",
            name="fb_link",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="brokers",
            name="is_activated",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="brokers",
            name="fb_id",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="post",
            name="message",
            field=models.CharField(max_length=500),
        ),
    ]
