# Generated by Django 5.0.1 on 2024-01-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_brokers_fb_link_brokers_is_activated_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.AddField(
            model_name="group",
            name="fb_last_post_timestamp",
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name="group",
            name="fb_link",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="brokers",
            name="fb_id",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
