# Generated by Django 5.0.1 on 2024-02-22 15:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_delete_post_group_fb_last_post_timestamp_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Keywords",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="PVA",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("proxy_ip", models.CharField(max_length=20)),
                ("username", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                ("cookies", models.CharField(default="", max_length=3000)),
            ],
        ),
        migrations.RemoveField(
            model_name="group",
            name="fb_id",
        ),
        migrations.RemoveField(
            model_name="group",
            name="fb_last_post_timestamp",
        ),
        migrations.AddField(
            model_name="group",
            name="last_post_link",
            field=models.CharField(default="", max_length=90),
        ),
        migrations.AlterField(
            model_name="group",
            name="fb_link",
            field=models.CharField(default="", max_length=90),
        ),
        migrations.AddField(
            model_name="group",
            name="pva",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.pva"),
        ),
    ]
