# Generated by Django 5.0.1 on 2024-02-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_keywords_pva_remove_group_fb_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="keywords",
            name="pva",
            field=models.ManyToManyField(to="api.pva"),
        ),
    ]
