# Generated by Django 5.0.1 on 2024-02-27 15:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_keywords_pva"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="pva",
        ),
        migrations.AddField(
            model_name="group",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.RenameModel(
            old_name="Brokers",
            new_name="Broker",
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=1000)),
                ("broker", models.ManyToManyField(to="api.broker")),
            ],
        ),
        migrations.DeleteModel(
            name="Keywords",
        ),
    ]
