# Generated by Django 5.0.1 on 2024-03-05 13:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_remove_group_pva_group_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="keyword",
            name="broker",
        ),
        migrations.AddField(
            model_name="broker",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="keyword",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pva",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="KeywordBroker",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("broker", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.broker")),
                ("keyword", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.keyword")),
            ],
        ),
        migrations.AddField(
            model_name="keyword",
            name="brokers",
            field=models.ManyToManyField(related_name="keywords", through="api.KeywordBroker", to="api.broker"),
        ),
    ]
