# Generated by Django 5.0.1 on 2024-03-12 15:27

import django.db.models.deletion
from django.db import migrations, models


def update_brokers(apps, schema_editor):
    Broker = apps.get_model("api", "Broker")
    Company = apps.get_model("api", "Company")

    try:
        default_company = Company.objects.get(name="LeadTrek default company")
    except Company.DoesNotExist:
        default_company = Company.objects.create(name="LeadTrek default company", is_staff=True)

    for broker in Broker.objects.all():
        broker.company = default_company
        broker.save()


def revert_update_brokers(apps, schema_editor):
    Broker = apps.get_model("api", "Broker")
    Broker.objects.update(company=None)


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_remove_group_fb_link_remove_group_last_post_link_and_more"),
    ]

    operations = [
        migrations.RunPython(update_brokers, reverse_code=revert_update_brokers),
        migrations.AlterField(
            model_name="broker",
            name="company",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.company"),
        ),
    ]
