# Generated by Django 5.0.1 on 2024-03-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_alter_broker_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broker",
            name="fb_link",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="group",
            name="fb_id",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
